### ISSUE TITLE
Link concepts to concepticon.

### ISSUE THREAD

**Issue by LinguList** [lexibank/simsrma#2]
The dataset by Sims on Proto-Rma is very neat in that it offers a limited amount of concept labels in a cross-semantic cognate set. What I just did in creating `etc/concepts.tsv` was to extract all these concepts which are the same (more or less) and keep the original glosses, which distinguish by adding small superscript characters. In this way, the data can be easily added to concepticon.

**Comment by LinguList** [comment]
We do this as part of the concepticon here: https://github.com/concepticon/concepticon-data/issues/813

**Comment by LinguList** [comment]
If anybody could look into this, this would be nice.

**Comment by chrzyki** [comment]
Sorry @LinguList, I meant to push this to a separate branch and open a PR ... instead I accidentally pushed to master. My bad. Should I revert and open a PR or is it okay if you check here?

https://github.com/lexibank/simsrma/commit/9c893d73f453c519f207deeceeebb91216d7ba26

**Comment by LinguList** [comment]
excellent, thanks!
